Location: IOExceptionWithCauseTest.java

Content: 

/** 

 * Tests the  {@link IOExceptionWithCause#IOExceptionWithCause(String,Throwable)} constructor.

 */

@Test public void testIOExceptionStringThrowable(){

  final Throwable cause=new IllegalArgumentException("cause");

  final IOException exception=new IOException("message",cause);

  this.validate(exception,cause,"message");

}

Location: IOExceptionWithCauseTest.java

Content: 

/** 

 * Tests the  {@link IOExceptionWithCause#IOExceptionWithCause(Throwable)} constructor.

 */

@Test public void testIOExceptionThrowable(){

  final Throwable cause=new IllegalArgumentException("cause");

  final IOException exception=new IOException(cause);

  this.validate(exception,cause,"java.lang.IllegalArgumentException: cause");

}

Location: IOExceptionWithCauseTest.java

Content: 

void validate(final Throwable throwable,final Throwable expectedCause,final String expectedMessage){

  assertEquals(expectedMessage,throwable.getMessage());

  assertEquals(expectedCause,throwable.getCause());

  assertSame(expectedCause,throwable.getCause());

}

